spring:
  application:
    name: HRbank_sb6_1
  servlet:
    multipart:
      maxFileSize: 10MB # ?? ??? ?? ??
      maxRequestSize: 30MB  #

  datasource:
    url: jdbc:postgresql://localhost:5432/hrbank
    username: team01
    password: team01
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: none   # ?? ????? validate ?? none ??
    show-sql: true        # ???? SQL ??. product ??? false
    properties:
      hibernate:
        format_sql: true   # SQL ?? ?? ??
        highlight_sql: true # (Hibernate 5.5+) ANSI ?? ??
        use_sql_comments: true # JPQL -> SQL ?? ? ?? ??
        # ??? ?????? ??(Dialect) ??
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false   # OSIV ???? (??? ????? ??? ??)

  sql:
    init:
      mode: never   # schema.sql, data.sql ?? ?? (never, embedded, always)

  hrbank:
    storage:
      local:
        root-path: .files

  logging:
    level:
      root: DEBUG
      org.hibernate.SQL: DEBUG            # ???? SQL ??
      org.hibernate.type.descriptor.sql: TRACE  # SQL? ????? ???? ? ??

      backup:
        schedule:
          rate: 36000000 #자동 백업 시간 현재: 10분
